export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const ALPHABET_LENGTH = 26;

export const LOWERCASE_INDEX = 97;
export const UPPERCASE_INDEX = 65;

export const MAX_KEY_LENGTH = 27;
export const ENGLISH_INDEX_OF_COINCIDENCE = 0.068;
export const RANDOM_INDEX_OF_COINCIDENCE = 0.038;